### ISSUE TITLE
Using imixs-marty with maven?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-marty#197]
Hi,
I want to use imixs-marty with maven in my existing project. I tried it with these dependencies:

```
		<dependency>
			<groupId>org.imixs.workflow</groupId>
			<artifactId>imixs-workflow-engine</artifactId>
			<version>${org.imixs.workflow.version}</version>
		</dependency>
		<dependency>
			<groupId>org.imixs.workflow</groupId>
			<artifactId>imixs-workflow-jax-rs</artifactId>
			<version>${org.imixs.workflow.version}</version>
		</dependency>
		<dependency>
			<groupId>org.imixs.workflow</groupId>
			<artifactId>imixs-workflow-faces</artifactId>
			<version>${org.imixs.workflow.version}</version>
		</dependency>
		<dependency>
			<groupId>org.imixs.marty</groupId>
			<artifactId>imixs-marty-ejb</artifactId>
			<version>3.0.7-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.imixs.marty</groupId>
			<artifactId>imixs-marty-util</artifactId>
			<version>3.0.7-SNAPSHOT</version>
		</dependency>
		
```

But I always get the following error message:

```
20:42:19,665 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC000001: Failed to start service jboss.deployment.unit."imixs-workflow-4.2.0-SNAPSHOT.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."imixs-workflow-4.2.0-SNAPSHOT.war".PARSE: WFLYSRV0153: Failed to process phase PARSE of deployment "imixs-workflow-4.2.0-SNAPSHOT.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: WFLYEE0040: A component named 'SetupService' is already defined in this module
	at org.jboss.as.ee.component.EEModuleDescription.addComponent(EEModuleDescription.java:167)
	at org.jboss.as.ejb3.deployment.processors.EJBComponentDescriptionFactory.addComponent(EJBComponentDescriptionFactory.java:58)
	at org.jboss.as.ejb3.deployment.processors.SessionBeanComponentDescriptionFactory.processSessionBeans(SessionBeanComponentDescriptionFactory.java:169)
	at org.jboss.as.ejb3.deployment.processors.SessionBeanComponentDescriptionFactory.processAnnotations(SessionBeanComponentDescriptionFactory.java:86)
	at org.jboss.as.ejb3.deployment.processors.AnnotatedEJBComponentDescriptionDeploymentUnitProcessor.processAnnotations(AnnotatedEJBComponentDescriptionDeploymentUnitProcessor.java:57)
	at org.jboss.as.ejb3.deployment.processors.AbstractDeploymentUnitProcessor.deploy(AbstractDeploymentUnitProcessor.java:76)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
	... 5 more
```

Is it a error of wildfly or can't I use marty like this?
I already tried to clean with maven, deleting deployment files of wildfly...

Thank you!

**Comment by rsoika** [comment]
Hi Chris,
if you use imixs-workflow in the current snapshot release 4.2.0-SNAPSHOT, then you should use marty in version 3.1.0-SNAPSHOT. (But you must build the marty project from sources in this case)

Make sure that your build does not contain different versions of one module. Take a look into the /lib/ folder of your final build (war). Maybe there are modules duplicate?

**Comment by chrisw14** [comment]
Hi Ralph,
no there is are no modules duplicate. But maybe it's better to wait when there is a release of imixs-workflow-4.2.0 and imixs-marty-3.1.0 ?!

**Comment by rsoika** [comment]
Yes if you can wait this would it make easier for you. 
The problem in wildfly with new EJB modules (newer versions) is always that wildfly still depends on the old services after redeployment. So in any case you should better undeploy old versions and restart wildfly once again. Also a look into the Folder [WILDFLY]/standalone/deployments/ can be helpful. Maybe there are old failed deployments?

**Comment by rsoika** [comment]
No the relases imixs-workflow-4.2.0 and imixs-marty-3.1.0 are avialable.
